# Greek translation for zim
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the zim package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
# 
# 
# TRANSLATORS:
# paxatouridis (el)
# 
# Project-Id-Version: zim
# Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>
# POT-Creation-Date: 2008-10-27 21:09+0100
# PO-Revision-Date: 2009-12-02 17:02+0000
# Last-Translator: paxatouridis <Unknown>
# Language-Team: Greek <el@li.org>
# MIME-Version: 1.0
# Content-Type: text/plain; charset=UTF-8
# Content-Transfer-Encoding: 8bit
# Plural-Forms: nplurals=2; plural=n != 1;
# X-Launchpad-Export-Date: 2010-01-10 10:44+0000
# X-Generator: Launchpad (build Unknown)

use utf8;

# Subroutine to determine plural:
sub {my $n = shift; $n != 1},

# Hash with translation strings:
{
  '%a %b %e %Y' => '',
  '<b>Delete page</b>

Are you sure you want to delete
page \'{name}\' ?' => '',
  '<b>Enable Version Control</b>

Version control is currently not enabled for this notebook.
Do you want to enable it ?' => '',
  '<b>Folder does not exist.</b>

The folder: {path}
does not exist, do you want to create it now?' => '',
  '<b>Page already exists</b>

The page \'{name}\'
already exists.
Do you want to overwrite it?' => '',
  '<b>Restore page to saved version?</b>

Do you want to restore page: {page}
to saved version: {version} ?

All changes since the last saved version will be lost !' => '',
  '<b>Upgrade calendar pages to 0.24 format?</b>

This notebook contains pages for dates using the format yyyy_mm_dd.
Since Zim 0.24 the format yyyy:mm:dd is used by default, creating
namespaces per month.

Do you want to upgrade this notebook to the new layout?
' => '',
  'Add \'tearoff\' strips to the menus' => '',
  'Application show two text files side by side' => '',
  'Application to compose email' => '',
  'Application to edit text files' => '',
  'Application to open directories' => '',
  'Application to open urls' => '',
  'Attach _File|Attach external file' => 'Ε_πισύναψη Αρχείου|Επισύναψη εξωτερικού αρχείου',
  'Attach external files' => 'Επισύναψη εξωτερικών αρχείων',
  'Auto-format entities' => 'Αυτόματη μορφοποίηση οντοτήτων',
  'Auto-increment numbered lists' => '',
  'Auto-link CamelCase' => '',
  'Auto-link files' => '',
  'Auto-save version on close' => '',
  'Auto-select words' => 'Αυτόματη επιλογή λέξεων',
  'Automatically increment items in a numbered list' => '',
  'Automatically link file names when you type' => '',
  'Automaticly link CamelCase words when you type' => '',
  'Automaticly select the current word when you toggle the format' => '',
  'Bold' => 'Έντονα',
  'Calen_dar|Show calendar' => '',
  'Calendar' => 'Ημερολόγιο',
  'Can not find application "bzr"' => 'Δεν βρέθηκε η εφαρμογή "brz"',
  'Can not find application "{name}"' => 'Δεν βρέθηκε η εφαρμογή "{name}"',
  'Can not save a version without comment' => '',
  'Can not save to page: {name}' => 'Δεν κατέστη δυνατή η αποθήκευση στη σελίδα: {name}',
  'Can\'t find {url}' => 'Δεν βρέθηκε η {url}',
  'Cha_nge' => 'Αλλα_γή',
  'Chars' => '',
  'Check _spelling|Spell check' => '',
  'Check checkbox lists recursive' => '',
  'Checking a checkbox list item will also check any sub-items' => '',
  'Choose {app_type}' => 'Επιλογή {app_type}',
  'Co_mpare Page...' => 'Σύ_γκριση Σελίδας',
  'Command' => 'Εντολή',
  'Comment' => 'Σχόλιο',
  'Compare this version with' => '',
  'Copy Email Address' => 'Αντιγραφή Διεύθυνσης Email',
  'Copy Location|Copy location' => 'Αντιγραφή Θέσης|Αντιγραφή θέσης',
  'Copy _Link' => '',
  'Could not delete page: {name}' => 'Δεν κατέστη δυνατή η διαγραφή της σελίδας: {name}',
  'Could not get annotated source for page {page}' => '',
  'Could not get changes for page: {page}' => '',
  'Could not get changes for this notebook' => '',
  'Could not get file for page: {page}' => '',
  'Could not get versions to compare' => '',
  'Could not initialize version control' => '',
  'Could not load page: {name}' => 'Δεν κατέστη δυνατή η φόρτωση της σελίδας: {name}',
  'Could not rename {from} to {to}' => 'Δεν κατέστη δυνατή η μετονομασία από {from} σε {to}',
  'Could not save page' => 'Δεν κατέστη δυνατή η αποθήκευση της σελίδας',
  'Could not save version' => 'Δεν κατέστη δυνατή η αποθήκευση έκδοσης',
  'Creating a new link directly opens the page' => '',
  'Creation Date' => 'Ημερομηνία Δημιουργίας',
  'Cu_t|Cut' => 'Απο_κοπή|Αποκοπή',
  'Current' => 'Τρέχουσα',
  'Customise' => 'Προσαρμογή',
  'Date' => 'Ημερομηνία',
  'Default notebook' => 'Προεπιλεγμένο σημειωματάριο',
  'Details' => 'Λεπτομέρειες',
  'Diff Editor' => '',
  'Diff editor' => '',
  'Directory' => 'Κατάλογος',
  'Document Root' => '',
  'E_quation...|Insert equation' => '',
  'E_xport...|Export' => 'Ε_ξαγωγή...|Εξαγωγή',
  'E_xternal Link...|Insert external link' => '',
  'Edit Image' => 'Επεξεργασία Εικόνας',
  'Edit Link' => '',
  'Edit Query' => '',
  'Edit _Source|Open source' => 'Επεξεργα_σία Πηγαίου Κώδικα|Επεξεργασία πηγαίου κώδικα',
  'Edit notebook' => 'Επεξεργασία σημειωματάριου',
  'Edit text files "wiki style"' => 'Επεξεργασία αρχείων κειμένου σε μορφή "wiki"',
  'Editing' => 'Επεξεργασία',
  'Email client' => 'Πελάτης email',
  'Enabled' => 'Ενεργό',
  'Equation Editor' => 'Επεξεργαστής Εξισώσεων',
  'Equation Editor Log' => '',
  'Expand side pane' => '',
  'Export page' => 'Εξαγωγή σελίδας',
  'Exporting page {number}' => 'Εξαγωγή σελίδας {number}',
  'Failed to cleanup SVN working copy.' => 'Η εκκαθάριση αντίγραφου εργασίας SVN απέτυχε.',
  'Failed to load SVN plugin,
do you have subversion utils installed?' => 'Αποτυχία φόρτωσης του πρόσθετου SVN.
έχετε εγκατεστημένο το subversion utils;',
  'Failed to load plugin: {name}' => '',
  'Failed update working copy.' => 'Η ενημέρωση του αντίγραφου εργασίας απέτυχε.',
  'File browser' => 'Πλοηγός αρχείων',
  'File is not a text file: {file}' => '',
  'Filter' => 'Φίλτρο',
  'Find' => 'Εύρεση',
  'Find Ne_xt|Find next' => '',
  'Find Pre_vious|Find previous' => '',
  'Find and Replace' => 'Εύρεση και Αντικατάσταση',
  'Find what' => '',
  'Follow new link' => '',
  'For_mat|' => '_Μορφή|',
  'Format' => 'Μορφή',
  'General' => 'Γενικά',
  'Go to "{link}"' => '',
  'H_idden|.' => 'Α_φανή',
  'Head _1|Heading 1' => '',
  'Head _2|Heading 2' => '',
  'Head _3|Heading 3' => '',
  'Head _4|Heading 4' => '',
  'Head _5|Heading 5' => '',
  'Head1' => '',
  'Head2' => '',
  'Head3' => '',
  'Head4' => '',
  'Head5' => '',
  'Height' => 'Ύψος',
  'Home Page' => '',
  'Icon' => 'Εικονίδιο',
  'Id' => '',
  'Include all open checkboxes' => '',
  'Index page' => '',
  'Initial version' => 'Αρχική έκδοση',
  'Insert Date' => 'Εισαγωγή Ημερομηνίας',
  'Insert Image' => 'Εισαγωγή Εικόνας',
  'Insert Link' => '',
  'Insert from file' => 'Ειγαγωγή από αρχείο',
  'Interface' => 'Διεπαφή',
  'Italic' => 'Πλάγια',
  'Jump to' => 'Μετάβαση σε',
  'Jump to Page' => 'Μετάβαση στη Σελίδα',
  'Lines' => 'Γραμμές',
  'Links to' => '',
  'Match c_ase' => '',
  'Media' => 'Πολυμέσα',
  'Modification Date' => 'Ημερομηνία Τροποποίησης',
  'Name' => 'Όνομα',
  'New notebook' => 'Νέο σημειωματάριο',
  'New page' => 'Νέα σελίδα',
  'No such directory: {name}' => 'Δεν υπάρχει ο κατάλογος: {name}',
  'No such file or directory: {name}' => 'Δεν υπάρχει τέτοιο αρχείο ή κατάλογος: {name}',
  'No such file: {file}' => '',
  'No such notebook: {name}' => 'Δεν υπάρχει τέτοιο σημειωματάριο: {name}',
  'No such page: {page}' => '',
  'No such plugin: {name}' => 'Δεν υπάρχει τέτοιο πρόσθετο: {name}',
  'Normal' => '',
  'Not Now' => 'Όχι Τώρα',
  'Not a valid page name: {name}' => 'Δεν είναι έγκυρο το όνομα σελίδας: {name}',
  'Not an url: {url}' => '',
  'Note that linking to a non-existing page
also automatically creates a new page.' => '',
  'Notebook' => 'Σημειωματάριο',
  'Notebooks' => 'Σημειωματάρια',
  'Open Document _Folder|Open document folder' => 'Άνοιγμα _Φακέλου Εγγράφων|Άνοιγμα φακέλου εγγράφων',
  'Open Document _Root|Open document root' => 'Άνοιγμα _Ρίζας Εγγράφων|Άνοιγμα ρίζας εγγράφων',
  'Open _Directory' => '',
  'Open notebook' => 'Άνοιγμα σημειωματάριου',
  'Other...' => '',
  'Output' => '',
  'Output dir' => '',
  'P_athbar type|' => 'Τύπος _διαδρομής|',
  'Page' => 'Σελίδα',
  'Page Editable|Page editable' => '',
  'Page name' => 'Όνομα σελίδας',
  'Pages' => 'Σελίδες',
  'Password' => 'Κωδικός πρόσβασης',
  'Please enter a comment for this version' => 'Εισαγάγετε σχόλιο για αυτήν την έκδοση',
  'Please enter a name to save a copy of page: {page}' => 'Εισαγάγετε όνομα για την αποθήκευση αντιγράφου της σελίδας: {page}',
  'Please enter a {app_type}' => 'Εισαγάγετε {app_type}',
  'Please give a page first' => '',
  'Please give at least a directory to store your pages.
For a new notebook this should be an empty directory.
For example a "Notes" directory in your home dir.' => '',
  'Please provide the password for
{path}' => '',
  'Please select a notebook first' => 'Επιλέξτε αρχικά σημειωματάριο',
  'Please select a version first' => '',
  'Plugin already loaded: {name}' => 'Το πρόσθετο έχει ήδη φορτωθεί: {name}',
  'Plugins' => 'Πρόσθετα',
  'Pr_eferences|Preferences dialog' => 'Προτιμήσ_εις|Διάλογος προτιμήσεων',
  'Preferences' => 'Προτιμήσεις',
  'Prefix document root' => '',
  'Print to Browser|Print to browser' => '',
  'Prio' => '',
  'Proper_ties|Properties dialog' => 'Προ_τιμήσεις|Διάλογος προτιμήσεων',
  'Properties' => 'Ιδιότητες',
  'Rank' => '',
  'Re-build Index|Rebuild index' => 'Αναδόμηση Ευρετηρίου|Αναδόμηση ευρετηρίου',
  'Recursive' => '',
  'Rename page' => 'Μετονομασία σελίδας',
  'Rename to' => 'Μετονομασία σε',
  'Replace _all' => 'Αντικατάσταση ό_λων',
  'Replace with' => 'Αντικατάσταση με',
  'SVN cleanup|Cleanup SVN working copy' => 'Εκκαθάριση SVN|Εκκαθάριση αντίγραφου εργασίας SVN',
  'SVN commit|Commit notebook to SVN repository' => '',
  'SVN update|Update notebook from SVN repository' => 'Ενημέρωση SVN|Ενημέρωση σημειωματάριου από το αποθετήριο SVN',
  'S_ave Version...|Save Version' => 'Α_ποθήκευση Έκδοσης...|Αποθήκευση Έκδοσης',
  'Save Copy' => 'Αποθήκευση Αντιγράφου',
  'Save version' => '',
  'Scanning tree ...' => 'Σάρωση δένδρου ...',
  'Search' => 'Αναζήτηση',
  'Search _Backlinks...|Search Back links' => 'Αναζήτηση _Προσερχόμενων Συνδέσμων...|Αναζήτηση προσερχόμενων συνδέσμων',
  'Select File' => 'Επιλογή Αρχείου',
  'Select Folder' => 'Επιλογή Φακέλου',
  'Send To...' => 'Αποστολή προς...',
  'Show cursor for read-only' => '',
  'Show the cursor even when you can not edit the page. This is useful for keyboard based browsing.' => '',
  'Slow file system' => '',
  'Source' => '',
  'Source Format' => '',
  'Start the side pane with the whole tree expanded.' => '',
  'Stri_ke|Strike' => '',
  'Strike' => '',
  'TODO List' => '',
  'Task' => '',
  'Tearoff menus' => 'Αποσπώμενα μενού',
  'Template' => 'Πρότυπο',
  'Text' => 'Κείμενο',
  'Text Editor' => 'Επεξεργαστής Κειμένου',
  'Text _From File...|Insert text from file' => 'Κείμενο Από Αρχείο...|Εισαγωγή κειμένου από αρχείο',
  'Text editor' => 'Επεξεργαστής κειμένου',
  'The equation failed to compile. Do you want to save anyway?' => '',
  'The equation for image: {path}
is missing. Can not edit equation.' => '',
  'This notebook does not have a document root' => '',
  'This page does not exist
404' => '',
  'This page does not have a document folder' => '',
  'This page does not have a source' => '',
  'This page was updated in the repository.
Please update your working copy (Tools -> SVN update).' => 'Η σελίδα ενημερώθηκε στο αποθετήριο
Παρακαλώ ενημερώστε το αντίγραφο εγρασίας (Εργαλεία -> Ενημέρωση SVN)',
  'To_day|Today' => '',
  'Toggle Chechbox \'V\'|Toggle checkbox' => '',
  'Toggle Chechbox \'X\'|Toggle checkbox' => '',
  'Underline' => 'Υπογράμμιση',
  'Updating links' => '',
  'Updating links in {name}' => '',
  'Updating..' => 'Ενημέρωση..',
  'Use "Backspace" to un-indent' => '',
  'Use "Ctrl-Space" to switch focus' => 'Χρήση "Ctrl-Space" για εναλλαγή εστίασης',
  'Use "Enter" to follow links' => '',
  'Use autoformatting to type special characters' => '',
  'Use custom font' => '',
  'Use the "Backspace" key to un-indent bullet lists (Same as "Shift-Tab")' => '',
  'Use the "Ctrl-Space" key combo to switch focus between text and side pane. If disabled you can still use "Alt-Space".' => '',
  'Use the "Enter" key to follow links. If disabled you still can use "Alt-Enter"' => '',
  'User' => 'Χρήστης',
  'User name' => 'Όνομα χρήστη',
  'Verbatim' => 'Αυτολεξί',
  'Versions' => 'Εκδόσεις',
  'View _Annotated...' => '',
  'View _Log' => 'Θεώρηση _Καταγραφής',
  'Web browser' => 'Πλοηγός διαδικτύου',
  'Whole _word' => 'Πλήρης _λέξη',
  'Width' => 'Πλάτος',
  'Word Count' => 'Καταμέτρηση Λέξεων',
  'Words' => 'Λέξεις',
  'You can add rules to your search query below' => '',
  'You can choose using either the <b>Bazaar</b> or the <b>Subversion</b> Version Control System.
Please click \'help\' to read about the system requirements.' => '',
  'You have no {app_type} configured' => '',
  'You need to restart the application
for plugin changes to take effect.' => '',
  'Your name; this can be used in export templates' => '',
  'Zim Desktop Wiki' => 'Zim Επιτραπέζιο Wiki',
  '_About|About' => '',
  '_All' => 'Όλ_α',
  '_Back|Go page back' => '',
  '_Bold|Bold' => '_Έντονα|Έντονα',
  '_Browse...' => '_Πλοήγηση',
  '_Bugs|Bugs' => '',
  '_Child|Go to child page' => '_Θυγατρική|Μετάβαση στην θυγατρική σελίδα',
  '_Close|Close window' => '_Κλείσιμο|Κλείσιμο παραθύρου',
  '_Contents|Help contents' => '_Περιεχόμενα|Περιεχόμενα βοήθειας',
  '_Copy Page...|Copy page' => '_Αντιγραφή Σελίδας...|Αντιγραφή σελίδας',
  '_Copy|Copy' => '_Αντιγραφή|Αντιγραφή',
  '_Date and Time...|Insert date' => '_Ημερομηνία και Ώρα...|Εισαγωγή ημερομηνίας',
  '_Delete Page|Delete page' => '_Διαγραφή Σελίδας|Διαγραφή σελίδας',
  '_Delete|Delete' => '_Διαγραφή|Διαγραφή',
  '_Discard changes' => 'Α_πόρριψη αλλαγών',
  '_Edit' => '_Επεξεργασία',
  '_Edit Equation' => '_Επεξεργασία Εξίσωσης',
  '_Edit Link' => '',
  '_Edit Link...|Edit link' => '',
  '_Edit|' => '_Επεξεργασία|',
  '_FAQ|FAQ' => '_FAQ|FAQ',
  '_File|' => '_Αρχείο|',
  '_Filter' => '_Φίλτρο',
  '_Find...|Find' => '_Εύρεση|Εύρεση',
  '_Forward|Go page forward' => '_Εμπρός|Μετάβαση στην εμπρός σελίδα',
  '_Go|' => 'Με_τάβαση|',
  '_Help|' => '_Βοήθεια|',
  '_History|.' => '_Ιστορικό|.',
  '_Home|Go home' => '',
  '_Image...|Insert image' => 'Ε_κόνα|Προσθήκη εικόνας',
  '_Index|Show index' => '',
  '_Insert' => 'Ε_ισαγωγή',
  '_Insert|' => 'Ε_ισαγωγή|',
  '_Italic|Italic' => '_Πλάγια|Πλάγια',
  '_Jump To...|Jump to page' => 'Ά_λμα Σε...|Άλμα στη σελίδα',
  '_Keybindings|Key bindings' => '',
  '_Link' => '',
  '_Link to date' => '',
  '_Link...|Insert link' => '',
  '_Link|Link' => '',
  '_Namespace|.' => '',
  '_New Page|New page' => '_Νέα Σελίδα|Νέα σελίδα',
  '_Next' => 'Επόμε_νο',
  '_Next in index|Go to next page' => '',
  '_Normal|Normal' => '',
  '_Notebook Changes...' => '_Αλλαγές Σημειωματάριου...',
  '_Open Another Notebook...|Open notebook' => 'Άν_οιγμα Νέου Σημειωματάριου...|Άνοιγμα σημειωματάριου',
  '_Open link' => '',
  '_Overwrite' => '_Υπεργραφή',
  '_Page' => '_Σελίδα',
  '_Page Changes...' => 'Αλλαγές _Σελίδας...',
  '_Parent|Go to parent page' => '_Μητρική|Μετάβαση στην μητρική σελίδα',
  '_Paste|Paste' => 'Ε_πικόλληση|Επικόλληση',
  '_Preview' => '_Προεπισκόπηση',
  '_Previous' => '_Προηγούμενο',
  '_Previous in index|Go to previous page' => '',
  '_Properties' => '',
  '_Quit|Quit' => 'Απο_χώρηση|Αποχώρηση',
  '_Recent pages|.' => 'Π_ρόσφατες σελίδες|.',
  '_Redo|Redo' => '',
  '_Reload|Reload page' => 'Επαναφό_ρτωση|Επαναφόρτωση σελίδας',
  '_Rename' => '_Μετονομασία',
  '_Rename Page...|Rename page' => '_Μετονομασία Σελίδας...|Μετονομασία σελίδας',
  '_Replace' => '_Αντικατάσταση',
  '_Replace...|Find and Replace' => '',
  '_Reset' => 'Ανάτα_ξη',
  '_Restore Version...' => '',
  '_Save Copy' => 'Αποθήκευ_ση Αντιγράφου',
  '_Save a copy...' => 'Αποθήκευ_ση ενός αντιγράφου...',
  '_Save|Save page' => 'Αποθήκευ_ση|Αποθήκευση σελίδας',
  '_Screenshot...|Insert screenshot' => '',
  '_Search...|Search' => 'Αναζήτη_ση...|Αναζήτηση',
  '_Search|' => 'Αναζήτη_ση|',
  '_Send To...|Mail page' => 'Απο_στολή προς...|Σελίδα ταχυδρομείου',
  '_Statusbar|Show statusbar' => '',
  '_TODO List...|Open TODO List' => '',
  '_Today' => '_Σήμερα',
  '_Toolbar|Show toolbar' => '_Γραμμή Εργαλείων|Εμφάνιση γραμμής εργαλείων',
  '_Tools|' => 'Ε_ργαλεία|',
  '_Underline|Underline' => '_Υπογράμμιση|Υπογράμμιση',
  '_Undo|Undo' => '_Αναίρεση',
  '_Update links in this page' => '',
  '_Update {number} page linking here' => [
    '',
    ''
  ],
  '_Verbatim|Verbatim' => '_Αυτολεξί|Αυτολεξί',
  '_Versions...|Versions' => 'Εκ_δόσεις...|Εκδόσεις',
  '_View|' => 'Εμ_φάνιση|',
  '_Word Count|Word count' => 'Καταμέτρηση _Λέξεων|Καταμέτρηση Λέξεων',
  'other...' => '',
  '{name}_(Copy)' => '{name}_(Αντίγραφο)',
  '{number} _Back link' => [
    '',
    ''
  ],
  '{number} item total' => [
    '',
    ''
  ]
};
